CREATE TABLE `tran` (
  `tcode` varchar(20) COLLATE utf8_bin NOT NULL COMMENT 'Transaction Code',
  `softcomp` varchar(30) COLLATE utf8_bin DEFAULT NULL COMMENT 'Software Component',
  `applposid` varchar(24) COLLATE utf8_bin DEFAULT NULL COMMENT 'Application component - PS_POSID',
  `applfctr` varchar(20) COLLATE utf8_bin DEFAULT NULL COMMENT 'Application component - FCTR_ID',
  `devclass` varchar(30) COLLATE utf8_bin DEFAULT NULL COMMENT 'Package',
  `devclassns` varchar(10) COLLATE utf8_bin DEFAULT NULL COMMENT 'Package name space',
  `devclassp` varchar(30) COLLATE utf8_bin DEFAULT NULL COMMENT 'Package parent',
  `progname` varchar(40) COLLATE utf8_bin DEFAULT NULL COMMENT 'ABAP Program name',
  `dypno` int(11) DEFAULT NULL COMMENT 'ABAP Program Dynpro number',
  `param` varchar(254) COLLATE utf8_bin DEFAULT NULL COMMENT 'TCode Parameter',
  `calledtcode` varchar(20) COLLATE utf8_bin DEFAULT NULL COMMENT 'Called transaction code (if exist)',
  `variant` varchar(14) COLLATE utf8_bin DEFAULT NULL COMMENT 'Variant',
  `calledprogname` varchar(40) COLLATE utf8_bin DEFAULT NULL COMMENT 'Called Program',
  `calledclass` varchar(30) COLLATE utf8_bin DEFAULT NULL COMMENT 'Called Class',
  `calledmethod` varchar(61) COLLATE utf8_bin DEFAULT NULL COMMENT 'Called Method',
  `key1` varchar(132) COLLATE utf8_bin DEFAULT NULL COMMENT 'Parameter transaction: Field name for parameter passing',
  `value1` varchar(50) COLLATE utf8_bin DEFAULT NULL COMMENT 'Parameter transaction: Value to be passed',
  `key2` varchar(132) COLLATE utf8_bin DEFAULT NULL,
  `value2` varchar(50) COLLATE utf8_bin DEFAULT NULL,
  `key3` varchar(132) COLLATE utf8_bin DEFAULT NULL,
  `value3` varchar(50) COLLATE utf8_bin DEFAULT NULL,
  `key4` varchar(132) COLLATE utf8_bin DEFAULT NULL,
  `value4` varchar(50) COLLATE utf8_bin DEFAULT NULL,
  `key5` varchar(132) COLLATE utf8_bin DEFAULT NULL,
  `value5` varchar(50) COLLATE utf8_bin DEFAULT NULL,
  `key6` varchar(132) COLLATE utf8_bin DEFAULT NULL,
  `value6` varchar(50) COLLATE utf8_bin DEFAULT NULL,
  `key7` varchar(132) COLLATE utf8_bin DEFAULT NULL,
  `value7` varchar(50) COLLATE utf8_bin DEFAULT NULL,
  `debug` varchar(254) COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (`tcode`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='Transaction Code';
