CREATE TABLE `abapdevc` (
  `DEVCLASS` varchar(30) COLLATE utf8_bin NOT NULL,
  `KORRFLAG` varchar(1) COLLATE utf8_bin DEFAULT NULL,
  `NAMESPACE` varchar(10) COLLATE utf8_bin DEFAULT NULL,
  `CREATED_ON` varchar(8) COLLATE utf8_bin DEFAULT NULL,
  `PACKAGE_KIND` varchar(1) COLLATE utf8_bin DEFAULT NULL,
  `IS_ENHANCEABLE` varchar(1) COLLATE utf8_bin DEFAULT NULL,
  `SWITCH_ID` varchar(30) COLLATE utf8_bin DEFAULT NULL,
  `DLVUNIT` varchar(30) COLLATE utf8_bin DEFAULT NULL,
  `COMPONENT` varchar(20) COLLATE utf8_bin DEFAULT NULL,
  `PARENTCL` varchar(30) COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (`DEVCLASS`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;


